/*
 * Copyright The Original Author or Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.jenkins.plugins.opentelemetry.job.runhandler;

import edu.umd.cs.findbugs.annotations.NonNull;
import hudson.Extension;
import hudson.model.Action;
import hudson.model.Item;
import hudson.model.Job;
import hudson.model.Run;
import io.jenkins.plugins.opentelemetry.semconv.ExtendedJenkinsAttributes;
import io.opentelemetry.api.trace.SpanBuilder;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.sdk.autoconfigure.spi.ConfigProperties;
import java.util.Collection;
import javaposse.jobdsl.plugin.actions.SeedJobAction;
import javaposse.jobdsl.plugin.actions.SeedJobTransientActionFactory;
import javax.inject.Inject;
import jenkins.YesNoMaybe;

/**
 * {@link RunHandler} that creates build spans for Jenkins jobs managed by the Job DSL plugin.
 * <p>
 * When the Job DSL seed job is detected, span names and template attributes are set accordingly.
 * Loaded only when the {@code job-dsl} plugin is present at runtime.
 */
@Extension(optional = true, dynamicLoadable = YesNoMaybe.YES)
public class JobDslRunHandler implements RunHandler {

    private SeedJobTransientActionFactory seedJobTransientActionFactory;

    private boolean collapseJobName;

    /**
     * Creates the handler while verifying the Job DSL plugin classes are available.
     *
     * @throws ClassNotFoundException when the Job DSL plugin is not installed
     */
    public JobDslRunHandler() throws ClassNotFoundException {
        // verify the class is available to force the contract `@Extension(optional = true)`
        Class.forName(SeedJobAction.class.getName());
    }

    /**
     * {@inheritDoc} Returns {@code true} when the run's job was generated by a Job DSL seed job.
     */
    @Override
    public boolean canCreateSpanBuilder(@NonNull Run<?, ?> run) {
        Job<?, ?> job = run.getParent();
        // perf optimization: directly lookup up in the SeedJobTransientActionFactory over
        // `job.getAction(SeedJobAction.class)`
        Collection<? extends Action> actions = seedJobTransientActionFactory.createFor(job);
        return !actions.isEmpty();
    }

    /**
     * {@inheritDoc} Sets Job DSL template attributes on the span builder.
     */
    @NonNull
    @Override
    public SpanBuilder createSpanBuilder(@NonNull Run<?, ?> run, @NonNull Tracer tracer) {
        Job<?, ?> job = run.getParent();
        // perf optimization: directly lookup up in the SeedJobTransientActionFactory over
        // `job.getAction(SeedJobAction.class)`
        Collection<? extends Action> actions = seedJobTransientActionFactory.createFor(job);

        SeedJobAction seedJobAction = (SeedJobAction) actions.stream()
                .filter(action -> action instanceof SeedJobAction)
                .findFirst()
                .orElseThrow(IllegalStateException::new);

        // TODO understand the difference between seedJobAction.getTemplateJob() and seedJobAction.getSeedJob()
        Item seedJob = seedJobAction.getSeedJob();

        String templateFullName;
        String templateUrl;
        String spanName;
        if (seedJob == null) {
            templateFullName = null;
            templateUrl = null;
            spanName = job.getFullName();
        } else {
            templateFullName = seedJob.getFullName();
            templateUrl = seedJob.getUrl();
            spanName = collapseJobName ? "Job from seed '" + templateFullName + "'" : job.getFullName();
        }

        SpanBuilder spanBuilder =
                tracer.spanBuilder(ExtendedJenkinsAttributes.CI_PIPELINE_RUN_ROOT_SPAN_NAME_PREFIX + spanName);
        if (templateFullName != null) {
            spanBuilder.setAttribute(ExtendedJenkinsAttributes.CI_PIPELINE_TEMPLATE_ID, templateFullName);
        }
        if (templateUrl != null) {
            spanBuilder.setAttribute(ExtendedJenkinsAttributes.CI_PIPELINE_TEMPLATE_URL, templateUrl);
        }
        return spanBuilder;
    }

    /**
     * {@inheritDoc} Reads the {@code otel.instrumentation.jenkins.job.dsl.collapse.job.name} config flag.
     */
    @Override
    public void configure(ConfigProperties config) {
        collapseJobName =
                Boolean.TRUE.equals(config.getBoolean("otel.instrumentation.jenkins.job.dsl.collapse.job.name"));
    }

    /**
     * {@inheritDoc} Returns a high ordinal so this handler is evaluated late in the chain.
     */
    @Override
    public int ordinal() {
        return Integer.MAX_VALUE - 1;
    }

    /**
     * Injects the {@link SeedJobTransientActionFactory} for looking up seed-job relationships.
     *
     * @param seedJobTransientActionFactory the factory to inject
     */
    @Inject
    public void setSeedJobTransientActionFactory(@NonNull SeedJobTransientActionFactory seedJobTransientActionFactory) {
        this.seedJobTransientActionFactory = seedJobTransientActionFactory;
    }
}
