---
services:
  jenkins:
    extends:
      file: services.yml
      service: jenkins
    networks:
      - jenkins
    environment:
      KIBANA_HOST: ${KIBANA_HOST:-http://localhost:5601}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST:-http://elasticsearch:9200}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME:-jenkins_logs_user}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD:-changeme}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://edot:4317}
    volumes:
      - type: bind
        source: ./config/jenkins-elastic.yml
        target: /var/jenkins_home/jcasc/jenkins.yml
        read_only: true
    depends_on:
      edot:
        condition: service_healthy

  jenkins-inbound-agent:
    extends:
      file: services.yml
      service: jenkins-inbound-agent
    networks:
      - jenkins

  api-key:
    extends:
      file: ../src/test/resources/elastic-stack.yml
      service: api-key
    networks:
      - jenkins
    depends_on:
      kibana:
        condition: service_healthy
  edot:
    extends:
      file: ../src/test/resources/elastic-stack.yml
      service: edot
    networks:
      - jenkins
    depends_on:
      api-key:
        condition: service_completed_successfully

  elasticsearch:
    extends:
      file: ../src/test/resources/elastic-stack.yml
      service: elasticsearch
    networks:
      - jenkins

  kibana:
    extends:
      file: ../src/test/resources/elastic-stack.yml
      service: kibana
    networks:
      - jenkins
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  jenkins:
    driver: local
  esdata:
    driver: local
  edot-config:
    driver: local

networks:
  jenkins:
    driver: bridge
